### ISSUE TITLE
Bug: b' d' l' not supported in default solver

### ISSUE THREAD

**Issue by prendradjaja** [torjusti/cube-solver#52]
Hello! This project's super useful to me, thanks for it!

How to reproduce:
- `cubeSolver.solve("b' ")` throws `Error: Invalid algorithm provided to algorithm parser`
- The same is true for d' and l'.
- I'm using cube-solver v2.4.0

Looks like this is an intended use case, since `cubeSolver.solve("f' ")` works.

In case it's helpful: I took a short look and saw that somewhere along the way in evaluating `.solve("b' ")`, we try to evaluate `invertAlgorithm("z'' ")`, which gets rejected as invalid for having `'` twice, but I wasn't able to track this down any further.

**Comment by torjusti** [comment]
Thanks and apoligies for the huge delay! I've fixed this and will be deploying it to NPM soon.
